### ISSUE TITLE
Grain boundary of Graphene

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wojdyr/gosam#2]
```
Dear gosam developer,

I would like to generate grain boundary of graphene? Would you please guide me 
how to make from a xyz file containing coordinates of graphene.

Many thanks and looking forward to your attention.

Regards,

Rajib 

```

Original issue reported on code.google.com by `rajib.la...@gmail.com` on 7 Jun 2012 at 7:52

**Comment by wojdyr** [comment]
Sorry, I haven't got notification about this issue and I just found it now, when migrating gosam from google code to github.
